### ISSUE TITLE
[!] Unknown Error in request.

### ISSUE THREAD

**Issue by AiratHalitov** [N3TC4T/InstaBrute#10]
Log file: https://yadi.sk/d/it5og-IP3GLVrD

**Comment by N3TC4T** [comment]
I think its beacuse proxies problem , anyway if you use good and private proxies you wont see this errors again

**Comment by AiratHalitov** [comment]
Ok

**Comment by AiratHalitov** [comment]
@N3TC4T 
Can you recommend good free proxy service and passwords dictionary?

**Comment by N3TC4T** [comment]
@AiratHalitov 
There is many website you can find private and good proxies , for the password list its depend on target .
