### ISSUE TITLE
How to run it ?

### ISSUE THREAD

**Issue by ksalreqabi** [N3TC4T/InstaBrute#11]
How to write username and password and proxy ? 
could you add all the file and what commend I need to use

**Comment by ksalreqabi** [comment]
Khallids-MacBook-Pro:hacki ksalreqabi$ python instabrute -u user_test -w words.txt -p proxys.txt -t 4 -d -v
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'instabrute': [Errno 2] No such file or directory

**Comment by ksalreqabi** [comment]
```
Khallids-MacBook-Pro:hacki ksalreqabi$ python instabrute -u user_test -w words.txt -p proxys.txt -t 4 -d -v
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'instabrute': [Errno 2] No such file or directory
```

**Comment by ksalreqabi** [comment]
```
Khallids-MacBook-Pro:hacki ksalreqabi$ python instabrute.py [-h] -u USERNAME -w WORD -p PROXY [-t THREAD] [-v] [-d]
usage: instabrute.py [-h] -u USERNAME -w WORD -p PROXY [-t THREAD] [-v] [-d]
instabrute.py: error: unrecognized arguments: [-h] [-t THREAD] [-v] [-d]
```

**Comment by ksalreqabi** [comment]
I do not know how to run it , I have already crate 3 txt files one for user and  password and proxy list,

**Comment by FrostyModz** [comment]
python instabrute.py -u USERNAMEHERE -w words.txt -p proxys.txt -t 4 -d -v works for me on my macbook pro.

**Comment by N3TC4T** [comment]
@ksalreqabi 
as @FrostyModz  said use like this : 

`instabrute.py -u USERNAMEHERE -w words.txt -p proxys.txt -t 4 -d -v`
