### ISSUE TITLE
from: too many arguments error

### ISSUE THREAD

**Issue by keethesh** [N3TC4T/InstaBrute#17]
Getting error when trying anything. 
Errors:

root@kali:~# cd InstaBrute/
root@kali:~/InstaBrute# ./instabrute.py -h
from: too many arguments
./instabrute.py: line 17: try:: command not found
^Cfrom: too many arguments
^C./instabrute.py: line 21: except: command not found
^Cfrom: too many arguments
^C./instabrute.py: line 26: try:: command not found
^C./instabrute.py: line 28: except: command not found
^C./instabrute.py: line 32: class: command not found
./instabrute.py: line 33: HEADER: command not found
./instabrute.py: line 34: OKGREEN: command not found
./instabrute.py: line 35: WARNING: command not found
./instabrute.py: line 36: FAIL: command not found
./instabrute.py: line 37: ENDC: command not found
./instabrute.py: line 38: BOLD: command not found
./instabrute.py: line 39: UNDERLINE: command not found
./instabrute.py: line 42: syntax error near unexpected token `('
./instabrute.py: line 42: `def check_proxy(q):'

**Comment by N3TC4T** [comment]
try with python 

`python instabrute.py`

**Comment by keethesh** [comment]
I tried but it's the same :/

**Comment by keethesh** [comment]
I tried again now and it's good, thanks!
