### ISSUE TITLE
bruteforcer stuck

### ISSUE THREAD

**Issue by Carlito007** [N3TC4T/InstaBrute#2]
***************************************
* Inastgarm Brute forcer              *
* Coded by N3TC@T                     *
* netcat[dot]av[at]gmail[dot]com      *
***************************************
[+] Username Loaded: ******
[+] Words Loaded: 16
[+] Proxy Loaded: 44

[-] Testing Proxy List...
 --[+]  117.16.46.63:3128
 --[+]  118.170.244.130:8998
 --[+]  118.173.235.204:8080
 --[+]  118.69.202.160:3128
 --[+]  12.199.120.188:3128
 --[+]  121.128.112.120:3128
 --[+]  122.116.102.113:3128
 --[+]  123.30.238.16:3128
 --[+]  128.199.157.55:3128
 --[+]  128.199.209.118:808
 --[+]  138.68.131.161:3128
 --[+]  139.162.19.103:3128
 --[+]  159.203.243.237:3128
[+] Online Proxy:  13
[+] Getting CSRF Token:
[+] CSRF Token : 6AbbYftu1Ju7UOkr44x17mlSH74w53cv

[!] Initializing Workers
[!] Start Cracking ...

**Comment by N3TC4T** [comment]
Hi 

Are you run script in Windows ?

**Comment by HacknModz** [comment]
@N3TC4T Have you skype?  I would like your help !

**Comment by N3TC4T** [comment]
@Carlito007 

Fixed in  b7e033a7ab725dfcf7d55a7dbe6ff884de60eb4c

and changed from multiproccessing to multithreading for better speed , proxy checking progress improve , ...
