### ISSUE TITLE
Updates and bugs

### ISSUE THREAD

**Issue by AiratHalitov** [N3TC4T/InstaBrute#4]
Can you update your file **instabrute.py**?
I fixed some bugs: https://yadi.sk/d/mwvE0XEj3CtuyD (for python 3)

And proxy is not working (Error in request). Can you fix this issue?

**Comment by N3TC4T** [comment]
Thanks 👍 
fixed in 7271bab20e5bc47ff6c30b193bb65cc4dc85d802
