### ISSUE TITLE
7 threads

### ISSUE THREAD

**Issue by AiratHalitov** [N3TC4T/InstaBrute#9]
Why here is only 7 threads?  (line 279) https://github.com/N3TC4T/InstaBrute/blob/master/instabrute.py#L279
`for workers in range(7):`
Need:
`for workers in range(max_thread):`

And add `max_thread = THREAD` to line 273

And delete all using `queuelock`

**Comment by AiratHalitov** [comment]
Here is new file instabrute.py with updates

https://yadi.sk/d/tD9L4gTj3GLbaT

**Comment by N3TC4T** [comment]
fixed Thanks .
anyway you can fork the repository and use pull request 👍
